openapi: 3.0.1
info:
  version: 0.1.0
  title: Subject Picker Action Group
  description: Describes routes to specific agent models
paths:
  /default:
    post:
      tags:
        - model
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/details"
        required: true
      responses:
        200:
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          description: Success
  /trading:
    post:
      tags:
        - model
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/details"
        required: true
      responses:
        200:
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          description: Success
        403:
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          description: User does not posses right subscription
          content:
            application/json:
              schema:
                title: "InvalidSubscription"
                type: "object"
                properties:
                  reason:
                    type: "string"
components:
  schemas:
    details:
      title: Task object
      required:
        - subject
        - task
      type: object
      properties:
        subject:
          type: string
          example: Trading
        task:
          type: string
          example: Check nvidia stocks
