name: aethera
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  amplify_flutter: ^2.4.1
  amplify_auth_cognito: ^2.4.1
  amplify_authenticator: ^2.1.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
