name: Lambdas - Deploy
on:
  push:
    branches:
      - main
    paths:
      - "packages/lambdas/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip Lambda function
        run: |
          zip -r9 lambda_function.zip . -x '*.git*'

      - name: Assume role from OICD provider
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: eu-central-1
      - name: Deploy code to s3
        run: |
          aws s3 cp lambda_function.zip s3://${{secrets.AWS_BUCKET_NAME}}/lambda_function.zip
      - name: Run Terraform plan
        uses: indiesdev/curl@v1.1
        with:
          url: https://app.terraform.io/api/v2/runs
          method: "POST"
          accept: 201
          headers: '{ "Content-Type": "application/vnd.api+json" }'
          bearer-token: ${{ secrets.TERRAFORM_TOKEN }}
          body: '{"data":{"type":"runs","attributes":{"message":"Triggered by GitHub Action","auto-apply":true},"relationships":{"workspace":{"data":{"type":"workspaces","id":"${{ secrets.TERRAFORM_WORKSPACEID }}"}}}}}'
          log-response: true
