name: Lambdas - Deploy
on:
  push:
    branches:
      - main
    paths:
      - "packages/lambdas/**"

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: packages/lambdas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: eu-central-1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies and package lambdas
        run: |
          for lambda in $(ls -d */ | sed 's|[/]||g'); do
            cd $lambda
            
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt -t .
            fi

            zip -r $lambda.zip .
            cd ..
          done

      - name: Sync with S3
        run: aws s3 sync . s3://${{secrets.AWS_BUCKET_NAME}} --exclude "*" --include "*.zip" --delete --acl public-read

      - name: Create terraform run to update lamdas from S3
        uses: indiesdev/curl@v1.1
        with:
          url: https://app.terraform.io/api/v2/runs
          method: "POST"
          accept: 201
          headers: '{ "Content-Type": "application/vnd.api+json" }'
          bearer-token: ${{ secrets.TERRAFORM_TOKEN }}
          body: '{"data":{"type":"runs","attributes":{"message":"Triggered by GitHub Action","auto-apply":true},"relationships":{"workspace":{"data":{"type":"workspaces","id":"${{ secrets.TERRAFORM_WORKSPACE_ID }}"}}}}}'
          log-response: true
